[build-system]
requires = ["setuptools>=69"]
build-backend = "setuptools.build_meta"

[project]
name = "rv_pytools"
version = "1.1.1"
authors = [
  { name="Rohan V", email="rvspamacc@gmail.com" },
]
description = "A package for general use in my programs"
readme = "docs/README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license-files = ["docs/LICENSE*"]
requires-python = ">=3.10"
dependencies = [
    "psycopg2-binary",
]

[project.urls]
Homepage = "https://github.com/riders994/rv_pytools"
Issues = "https://github.com/riders994/rv_pytools/issues"

[project.optional-dependencies]
dev = ["pytest"]

[tool.setuptools.packages.find]
exclude = ["tests*"]

[tool.pytest.ini_options]
testpaths = ["tests"]
